services:
  - type: web
    name: automatisch-main
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    repo: https://github.com/automatisch/automatisch
    plan: free  # Use the free-tier instance
    autoDeploy: false
    envVars:
      - key: HOST
        fromService:
          name: automatisch-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        fromDatabase:
          name: automatisch-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: automatisch-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: automatisch-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: automatisch-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: automatisch-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: automatisch-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: automatisch-redis
          property: port
      - fromGroup: common-env-vars

  - type: redis
    name: automatisch-redis
    plan: free  # Use free-tier Redis (non-persistent)
    ipAllowList: []  # Only allow internal connections
    maxmemoryPolicy: allkeys-lru  # Automatically remove least-used keys to save space

databases:
  - name: automatisch-database
    databaseName: automatisch
    plan: free  # Use free-tier PostgreSQL (may have size & performance limits)

envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: PROTOCOL
        value: https
      - key: PORT
        value: 443
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true
